services:
  database:
    image: postgres
    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: kephas
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres

    volumes:
      - db:/data/postgres

    restart: unless-stopped


volumes:
  db:
