services:
  database:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bookstore
      POSTGRES_USER: kephas
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    restart: unless-stopped

  app:
    image: dockerninja725/bookstorespi:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/bookstore
      SPRING_DATASOURCE_USERNAME: kephas
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - database
    restart: unless-stopped

volumes:
  db:
