spring:
  application:
    name: BookStoreApi

  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: kephas
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true